---
- name: Update hwdb
  command: systemd-hwdb update
  listen: Rebuild hwdb

- name: Trigger udev reload
  command: udevadm trigger
  listen: Rebuild hwdb

- name: Restart systemd-udevd
  service:
    name: systemd-udevd.service
    state: restarted
